### ISSUE TITLE
Typo in the download command

### ISSUE THREAD

**Issue by rfarouni** [BackofenLab/CRISPRloci#1]
Hi,

There was an extra v in the command . It should be the following 

`wget https://github.com/BackofenLab/CRISPRloci/archive/1.0.0.tar.gz`

instead of 

`wget https://github.com/BackofenLab/CRISPRloci/archive/v1.0.0.tar.gz`

**Comment by Edison2021** [comment]
Hi Alex
Could you please correct the typo?

Thanks
Edison

**Comment by Alexander-Mitrofanov** [comment]
Thank you very much for spotting the mistake!
Fixed
