### ISSUE TITLE
Conda creating was failed, UnsatisfiableError: The following specifications were found to be incompatible with each other:

### ISSUE THREAD

**Issue by wh277** [BackofenLab/CRISPRloci#9]
Almostly all the dependences could not be installed

**Comment by aelbehery** [comment]
I am experiencing the same error.
@wh277 Why did you close the issue? How could you solve it? Any advice?
The error log is attached.
[conda_error_log.txt](https://github.com/BackofenLab/CRISPRloci/files/13199204/conda_error_log.txt)

**Comment by wh277** [comment]
I use CRISPRone instead

**Comment by aelbehery** [comment]
@Alexander-Mitrofanov and @amri2k Please, help with this error, I think the CRISPRloci-env.yml dependencies need to be revised. They have incompatibilities between versions.
